spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/site_film
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when-missing
      chat:
        options:
          model: phi3:mini
          temperature: 0.7
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            schema: ai_service
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        schema-validation: true
        dimensions: 1536
        schema-name: ai_service

server:
  port: 8443

logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.ai.chat.memory: DEBUG
    org.springframework.ai.chat.memory.repository.jdbc: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG