spring:
  liquibase:
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/site_film?currentSchema=ai_service
    username: user
    password: user
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2:7b
      init:
        pull-model-strategy: when_missing
      embedding:
        options:
          model: mxbai-embed-large
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            schema: ai_service


    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        schema-validation: true
        dimensions: 1024
        schema-name: ai_service
        table-name: vector_store

server:
  port: 8445
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: mypass
#    key-store-type: PKCS12
#    key-alias: localhost-cert
#    enabled-protocols: TLSv1.2,TLSv1.3
#    protocol: TLS