spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/site_film
    username: user
    password: user
  ai:
    ollama:
      base-url: http://localhost:11434       # Укажи URL сервера Ollama
      init:
        pull-model-strategy: when-missing     # Загружать модель при старте, если нет
      chat:
        options:
          model: phi3:mini                    # Имя модели (можно изменить)                     # отключить потоковый вывод
          temperature: 0.7                    # тон генерации (0.0–1.0)
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            schema: ai_service

    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        schema-validation: true
        dimensions: 1536
        schema-name: ai_service
        table-name: vector_store
server:
  port: 8443