spring:
  application:
    name: user-service
  datasource:
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/site_film
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/site-film
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: user-service
            client-secret: R6wJRDdSitRYeTng89eEKT3aJtekNzJr
            scope:
              - view_content
              - microprofile-jwt
              - openid

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true