spring:
  application:
    name: admin-service

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      client-id: email-producer

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/site_film
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${SERVER_PORT:8081}
