spring:
  application:
    name: content-service
  datasource:
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/site_film
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true